AllCops:
  NewCops: enable 
Layout/EndAlignment:
  AutoCorrect: true
Style/SymbolArray:
  MinSize: 3
Style/HashSyntax:
  EnforcedShorthandSyntax: never 
Naming/VariableName:
  Exclude:
    - 'app/controllers/purchase.rb'

Metrics:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/SafeNavigation:
  Enabled: false
Style/RedundantBegin:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/OpenStructUse:
  Enabled: false  
Style/FetchEnvVar:
  Enabled: false
Style/NumericPredicate:
  Enabled: false  
Style/HashLikeCase:
  Enabled: false  
Layout/LineLength:
  Enabled: false
Lint/ShadowingOuterLocalVariable:
  Enabled: false
Lint/Debugger:
  Enabled: false
Lint/UriEscapeUnescape:
  Enabled: false
Lint/DuplicateBranch:
  Enabled: false
Lint/SuppressedException:
  Enabled: false
