services:
- type: web
  name: dandelion-web
  env: ruby
  plan: free
  buildCommand: "bundle config path vendor/bundle && bundle install --jobs 4 --retry 3"
  startCommand: "bundle exec puma -C config/puma.rb production"
  autoDeploy: false
  envVars:
  - key: FRONTEND_URL
    fromService:
      type: web
      name: dandelion-web
      envVarKey: RENDER_EXTERNAL_URL
  - key: PORT
    value: 3000
  - key: MONGODB_URI
    fromService:
      type: pserv
      name: mongodb
      property: hostport

#- type: pserv
  #name: dandelion-db
  #env: docker
  #plan: free
  #autoDeploy: false
