name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v2

    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.3

    - name: Install MongoDB
      uses: supercharge/mongodb-github-action@1.3.0
      with:
        mongodb-version: 7.0

    - name: Cache gems
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Install gems
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3

    - name: Run RuboCop
      run: bundle exec rubocop --fail-level warning --display-only-fail-level-offenses

    - name: Run tests
      env:
        RACK_ENV: test
        PORT: 8020
        BASE_URI: http://127.0.0.1:8020
        DOMAIN: dandelion.events
        DEFAULT_CURRENCY: USD
        DEFAULT_TIME_ZONE: London
        SESSION_SECRET: 03f9674cbd548377
        STRIPE_PK: pk_test_hBG6G5aSlQWzUuSesRvMMj3v
        STRIPE_SK: sk_test_HCthlytw40KUFZ5nWNc0XI6A        
        CI: true
        SKIP_TOURS: true
      run: bundle exec rake test

      