name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test_file: [accounts, activities, events, gatherings, how_to_create_a_gathering, how_to_create_an_event, local_groups, nav, organisations, pmails, tour]
    steps:
    - name: Git checkout
      uses: actions/checkout@v4

    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.8
        bundler-cache: true

    - name: Install MongoDB
      uses: supercharge/mongodb-github-action@1.12.0
      with:
        mongodb-version: 7.0

    - name: Run RuboCop
      run: bundle exec rubocop --fail-level warning --display-only-fail-level-offenses

    - name: Run test (${{ matrix.test_file }})
      uses: nick-fields/retry@v3
      with:
        timeout_minutes: 10
        max_attempts: 3
        command: bundle exec rake test:${{ matrix.test_file }}
      env:
        RACK_ENV: test
        PORT: 8020
        BASE_URI: http://127.0.0.1:8020
        DOMAIN: dandelion.events
        DEFAULT_CURRENCY: USD
        DEFAULT_TIME_ZONE: Europe/London
        SESSION_SECRET: ${{ github.run_id }}
        STRIPE_PK: pk_test_hBG6G5aSlQWzUuSesRvMMj3v
        STRIPE_SK: sk_test_HCthlytw40KUFZ5nWNc0XI6A        
        CI: true
        SKIP_TOURS: true
      